[project]
name = 'Decentralized-Security-Quantum-Surveillance-Networks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.privacy-protection]
path = 'contracts/privacy-protection.clar'
clarity_version = 2
epoch = 2.5

[contracts.response-coordination]
path = 'contracts/response-coordination.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
